language: java
jdk: openjdk8
script: ./gradlew assemble test
sudo: required

before_install:
     - chmod +x gradlew

cache:
 directories:
  — $HOME/.gradle

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file: build/libs/SmartTomcat*.jar
  on:
    tags: true
